// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxFZe8TsR0l3UxNcxlzc26VDPE0hFvj7Y',
    appId: '1:492906693414:web:29e295ac13fdd395dd37e7',
    messagingSenderId: '492906693414',
    projectId: 'pgrocery-eab14',
    authDomain: 'pgrocery-eab14.firebaseapp.com',
    storageBucket: 'pgrocery-eab14.appspot.com',
    measurementId: 'G-6J4ZKX4XRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhrEQgU8kZG9SwWitchl8YHl7cPNlM3yI',
    appId: '1:492906693414:android:d9f36baf0af4a60ddd37e7',
    messagingSenderId: '492906693414',
    projectId: 'pgrocery-eab14',
    storageBucket: 'pgrocery-eab14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ8HrcyL6U6EICsJ3JgKf6KOr6y-222KE',
    appId: '1:492906693414:ios:93b00797c891e2fcdd37e7',
    messagingSenderId: '492906693414',
    projectId: 'pgrocery-eab14',
    storageBucket: 'pgrocery-eab14.appspot.com',
    iosBundleId: 'com.example.groceryp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ8HrcyL6U6EICsJ3JgKf6KOr6y-222KE',
    appId: '1:492906693414:ios:93b00797c891e2fcdd37e7',
    messagingSenderId: '492906693414',
    projectId: 'pgrocery-eab14',
    storageBucket: 'pgrocery-eab14.appspot.com',
    iosBundleId: 'com.example.groceryp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxFZe8TsR0l3UxNcxlzc26VDPE0hFvj7Y',
    appId: '1:492906693414:web:934fa53e6db55798dd37e7',
    messagingSenderId: '492906693414',
    projectId: 'pgrocery-eab14',
    authDomain: 'pgrocery-eab14.firebaseapp.com',
    storageBucket: 'pgrocery-eab14.appspot.com',
    measurementId: 'G-5DQ72LV9K5',
  );
}
